name: Build Docker Image

on:
    push:
        branches:
            - feature/embed

jobs:
    build_and_push:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: make build

            - name: Docker login
              run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            #- name: Log into registry
            #  run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ${{ secrets.DOCKER_HOST }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Push image
              run: make push
