name: Build Docker Image

on:
  push:
    branches:
      - feature/embed

jobs:
  build_and_push:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker login (Docker Hub)
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: make build

      - name: Push image
        run: make push
